baseURL = "https://newinh.me"
languageCode = "en-us"
title = "SeungHoon Shin"
theme = "awesome-identity"
# Enable Emoji emoticons support for page content
enableEmoji = true


## Profile Configurations
[params.profile]
  portrait = "/images/me.jpg"
  firstname = "Seunghoon"
  lastname = "Shin"
  title = "Software Enginner ∙ Back-end"
  bio = """TODO"""


## Contacts Configurations
[params.contacts]
  email = "newinh90@gmail.com"
  github = "newinh"
  linkedin = "newinh"
  stackoverflow = "6933079"


## Actions Configurations
[[params.actions]]
  name = "Resume"
  url = "files/resume.pdf"

## Footer Configurations
[params.footer]
  copyright = "© 2019 Seunghoon Shin. [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)."
  poweredBy = true
